services:
  db:
    image: postgres:14
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
